### ISSUE TITLE
Seek bar for currently playing sound

### ISSUE THREAD

**Issue by KyriiiX** [Tom4nt/Mega-Soundboard#18]
Hello ! First of all, thank you for creating this software.

In the next version of Mega Sounboard, could you add a clickable seek bar for the currently playing sound ? It's the only issue preventing me from using this software on a daily basis.

Greetings,
KyriiiX

**Comment by Tom4nt** [comment]
Done in 8df3c64fd407270e94b5b5d967e5c535ae789233
