### ISSUE TITLE
TypeError: Failed to set the 'volume' property

### ISSUE THREAD

**Issue by mrskizzex** [Tom4nt/Mega-Soundboard#23]
**Describe the bug**
Error when trying to play sound

**To Reproduce**
Try to play sound 

**Expected behavior**
Sound plays 

**Screenshots**
![image](https://user-images.githubusercontent.com/11503128/123563009-7874c080-d7b2-11eb-98e6-814538146809.png)

**Environment (please complete the following information):**
 - OS and version: Win10 20H2
 - Mega Soundboard version 0.5.1

**Comment by Tom4nt** [comment]
Thank you for reporting the issue.
Can you please provide more information by answering the following questions?
- Does this happen on all sounds or just that one?
- Have you changed the volume on the slider. If so, was it changed when adding the sound or by editing (after adding).
- Is it fixed if you restart the app?

I'm asking these questions because I can't reproduce the issue just by trying to play the sound.

**Comment by mrskizzex** [comment]
> * Does this happen on all sounds or just that one?
All sounds, EXP Soundboard plays them fine.
> * Have you changed the volume on the slider. If so, was it changed when adding the sound or by editing (after adding).
It happens when adding new sound and not touching any sliders and also after touching all sliders and putting them to different values.
> * Is it fixed if you restart the app?
Nope.

I wanted to add that I first downloaded SourceForge version 0.2.1 and the sounds were being played when using it, but on another restart it prompted an update and stopped working.
I tried reinstalling it but it didn't clear the settings. Could you tell me where they are saved so I can try clearing them first?

**Comment by Tom4nt** [comment]
It's weird that changing slider values does not fix the problem.

The file that stores volumes is located in the default `%appdata%` folder. Then `MegaSoundboard/Soundboards.json`.
It contains readable json of all soundboards and sounds.
Can you check if the property `volume` of each sound as a value between 0 and 100?

Thanks

**Comment by mrskizzex** [comment]
Deleting the settings folder (both of them MegaSoundboard and mega-soundboard) fixed the issue i was having. 
Probably updating from 0.2.1 breaks something.

To answer your question I did check that every slider was between 0 and 100. There was only one sound when i was testing after i removed them all manually.
