### ISSUE TITLE
Bulk add button doesn't work

### ISSUE THREAD

**Issue by mrskizzex** [Tom4nt/Mega-Soundboard#24]
**Describe the bug**
Bulk add doesn't work, button ADD doesn't produce results and spits errors into console.

**Screenshots**
![image](https://user-images.githubusercontent.com/11503128/123564165-8c232580-d7b8-11eb-909e-6fa1f3e5b6c9.png)

**Environment (please complete the following information):**
 - OS and version: Win10 20H2
 - Mega Soundboard version 0.5.1

**Comment by Tom4nt** [comment]
I was able to reproduce the issue and find the cause. It will be fixed in the next patch.
Thank you.

**Comment by Tom4nt** [comment]
Fixed in 14fdf5c907bef5f24f42ecdd16a6fce0a12d888a
