### ISSUE TITLE
Unable to assign F5 key to a sound clip

### ISSUE THREAD

**Issue by migouelBL** [Tom4nt/Mega-Soundboard#31]
**Describe the bug**
Assigning the F5 key to a sound will refresh the app and close the edit sound window

**To Reproduce**
Select sound, record key binding, press F5

**Expected behavior**
F5 key is properly assigned to the sound

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Windows 11
 - Mega Soundboard version 0.5.2

**Additional context**
N/A

**Comment by Tom4nt** [comment]
This can only be fixed by disabling the refresh functionality (F5 or Ctrl+R) either globally or while recording keys. Refreshing is not really needed so I think it's no problem disabling it globally. I'll do it when I get a chance.
Thanks for contributing.

**Comment by Tom4nt** [comment]
Fixed in [097b009](https://github.com/Tom4nt/Mega-Soundboard/commit/097b009972acdd8867c9086900727c6dc62230e9). Will be included in the next version.
