### ISSUE TITLE
IP camera monitoring

### ISSUE THREAD

**Issue by gbsinatra** [Tom4nt/Mega-Soundboard#41]
*A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.*

*Steps to reproduce the behavior. This is important.*

Environment:
 - OS and version: [e.g. Windows 10]
 - Mega Soundboard version [e.g. 0.3.0]

**Comment by Tom4nt** [comment]
Can you add details?

**Comment by Tom4nt** [comment]
Closed due to lack of feedback.
