### ISSUE TITLE
No Loop Option

### ISSUE THREAD

**Issue by SystemetricLabs** [Tom4nt/Mega-Soundboard#50]
Unable to allow a Sound to Loop after playback has finished.

*Steps to reproduce the behavior. This is important.*
Play the sound, wait for it to finish, no looping possible, sound stops

Environment:
 - OS and version: [e.g. Windows 10]
 - Mega Soundboard version [e.g. 0.3.0]

**Comment by Tom4nt** [comment]
This is a feature request, right?
A setting to enable/disable looping (and a keybind for it) will be one of the next features to be implemented.
Thank you for your feedback.

**Comment by Tom4nt** [comment]
Done in 4edfdea
