### ISSUE TITLE
Parts of a sound grouped

### ISSUE THREAD

**Issue by Noctabou** [Tom4nt/Mega-Soundboard#55]
There is another thing i would like to see (and i kinda want to help you, even thought i need to learn)
I often cut one sound into multiple parts. Or even have 5 sounds that are the same kind, but with different intonation...
I'd like having a dropdown showing every sounds grouped in one block. And if you click this block, it plays a default sound (maybe the first one of the group, or let the user select the default sound).

I've made a mockup :
![Sans titre3](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/246bdc15-ccf1-4737-bd10-29da65947d51)

**Comment by Tom4nt** [comment]
Thanks for your suggestion. I think this is a good addition. Maybe the group could be created by dragging a sound on top of another with the `Shift` key pressed. Of course, some kind of hint would appear so people don't have to guess.

**Comment by Tom4nt** [comment]
Completed. Soon to be released.
