### ISSUE TITLE
Control dock being too wide (or playing bar being invisible instead of disappearing)

### ISSUE THREAD

**Issue by Noctabou** [Tom4nt/Mega-Soundboard#56]
*A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.*
The dock at the bottom right of the app is wider than displayed. It blocks clics where the play bar appears.
Because i have a lot of sounds on MegaSoundboard, i often want to click on the last sound displayed on screen, but the clic doesn't start the sound.

*Steps to reproduce the behavior. This is important.*
Try clicking in left side of the controls, it shouldn't play the sound.
![image](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/dab6c9ac-d8b5-4f5c-9380-bf3ac12f7739)

Environment:
 - OS and version: Windows 11
 - Mega Soundboard version 0.6.3

**Comment by Tom4nt** [comment]
Thank you. This will be fixed soon. Keep in mind that you can resize the window to fit more sounds.

**Comment by Noctabou** [comment]
I know, but resizing MegaSoundboard on my 768p screen, ehh it takes a lot of space. I think a Zoom slider could also be a good addition

**Comment by Tom4nt** [comment]
Zooming should be easy to implement. I'll create an issue for it.
